import { regex_placement } from "@/services/RegexEngine";
import type { RegexScript } from "@/types/character";
import { describe, expect, it } from "vitest";
import {
  applyHtmlTemplateRules,
  buildHtmlTemplatePrompt,
  hasRenderableHtmlBlock,
} from "../HtmlTemplateEngine";

function makeRule(overrides: Partial<RegexScript>): RegexScript {
  return {
    id: "rule-1",
    scriptName: "rule",
    findRegex: "/<card>([\\s\\S]*?)<\\/card>/g",
    replaceString: "",
    trimStrings: [],
    placement: [regex_placement.AI_OUTPUT],
    disabled: false,
    markdownOnly: false,
    promptOnly: false,
    runOnEdit: false,
    substituteRegex: 0,
    minDepth: -1,
    maxDepth: -1,
    isHtmlTemplate: true,
    htmlTemplate: "<div>{{1.title}}</div>",
    cssScope: ".card{color:red}",
    aiPrompt: "請讓 {{char}} 輸出 <card>JSON</card>",
    parseMode: "json",
    renderMode: "iframe",
    order: 0,
    ...overrides,
  };
}

describe("HtmlTemplateEngine", () => {
  it("renders json templates into fenced html at the original position", () => {
    const result = applyHtmlTemplateRules(
      "前 <card>{\"title\":\"測試\"}</card> 後",
      [makeRule({})],
      { characterName: "阿水", userName: "User", placement: regex_placement.AI_OUTPUT },
    );

    expect(result.applied).toBe(1);
    expect(result.htmlBlocks).toHaveLength(1);
    expect(result.text).toContain("前");
    expect(result.text).toContain("後");
    expect(result.text).toContain("```html");
    expect(result.text).toContain("<style>.card{color:red}</style><div>測試</div>");
  });

  it("escapes AI-provided values before inserting them into templates", () => {
    const result = applyHtmlTemplateRules(
      "<card>{\"title\":\"<script>alert(1)</script>\"}</card>",
      [makeRule({})],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.text).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
    expect(result.text).not.toContain("<script>alert(1)</script>");
  });

  it("supports kv parse mode", () => {
    const result = applyHtmlTemplateRules(
      "<card>title=銀行卡\namount:100</card>",
      [makeRule({ parseMode: "kv", htmlTemplate: "<div>{{1.title}} {{1.amount}}</div>" })],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.text).toContain("<div>銀行卡 100</div>");
  });

  it("skips rules whose placement does not match", () => {
    const result = applyHtmlTemplateRules(
      "<card>{\"title\":\"測試\"}</card>",
      [makeRule({ placement: [regex_placement.USER_INPUT] })],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.applied).toBe(0);
    expect(result.text).toBe("<card>{\"title\":\"測試\"}</card>");
  });

  it("fast-path skips tag templates when the trigger tag is absent", () => {
    const result = applyHtmlTemplateRules(
      "普通對話內容",
      [makeRule({})],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.applied).toBe(0);
    expect(result.htmlBlocks).toHaveLength(0);
    expect(result.text).toBe("普通對話內容");
  });

  it("keeps compatibility for non-tag regex templates", () => {
    const result = applyHtmlTemplateRules(
      "score: 99",
      [
        makeRule({
          findRegex: "/score:\\s*(\\d+)/g",
          parseMode: "text",
          htmlTemplate: "<div>分數 {{$1}}</div>",
        }),
      ],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.applied).toBe(1);
    expect(result.text).toContain("<div>分數 99</div>");
  });

  it("builds html template prompts with global macros", () => {
    const prompt = buildHtmlTemplatePrompt([makeRule({})], {
      characterName: "阿水",
      placement: regex_placement.AI_OUTPUT,
    });

    expect(prompt).toContain("阿水");
    expect(prompt).toContain("<card>JSON</card>");
  });

  it("detects renderable fenced html generated by display regex", () => {
    expect(hasRenderableHtmlBlock("文字\n```html\n<div>卡片</div>\n```")).toBe(true);
    expect(hasRenderableHtmlBlock("普通文字")).toBe(false);
  });

  // ===== inline 渲染模式（Shadow DOM）=====
  it("inline mode wraps output in <aguaphone-inline-card> with embedded css", () => {
    const result = applyHtmlTemplateRules(
      "前 <card>{\"title\":\"狀態\"}</card> 後",
      [makeRule({ renderMode: "inline" })],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.applied).toBe(1);
    expect(result.htmlBlocks).toHaveLength(1);
    expect(result.text).toContain("前");
    expect(result.text).toContain("後");
    // inline 模式不包 ```html``` fence（避免被 iframe 路徑捕獲）
    expect(result.text).not.toContain("```html");
    // 但 cssScope 內嵌進自訂元素，由 shadow root 隔離
    expect(result.text).toContain("<aguaphone-inline-card>");
    expect(result.text).toContain("</aguaphone-inline-card>");
    expect(result.text).toContain("<style>.card{color:red}</style>");
    expect(result.text).toContain("<div>狀態</div>");
  });

  it("inline mode without cssScope omits the <style> block", () => {
    const result = applyHtmlTemplateRules(
      "<card>{\"title\":\"X\"}</card>",
      [makeRule({ renderMode: "inline", cssScope: "" })],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.text).toBe("<aguaphone-inline-card><div>X</div></aguaphone-inline-card>");
  });

  it("inline mode still escapes AI-provided values", () => {
    const result = applyHtmlTemplateRules(
      "<card>{\"title\":\"<img src=x onerror=alert(1)>\"}</card>",
      [makeRule({ renderMode: "inline" })],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.text).toContain("&lt;img src=x onerror=alert(1)&gt;");
    expect(result.text).not.toContain("<img src=x");
  });

  it("inline mode supports each-loops over JSON arrays", () => {
    const result = applyHtmlTemplateRules(
      "<list>{\"items\":[{\"n\":\"A\"},{\"n\":\"B\"}]}</list>",
      [
        makeRule({
          findRegex: "/<list>([\\s\\S]*?)<\\/list>/g",
          renderMode: "inline",
          parseMode: "json",
          htmlTemplate: "<ul>{{#each:1.items}}<li>{{n}}</li>{{/each}}</ul>",
          cssScope: "",
        }),
      ],
      { placement: regex_placement.AI_OUTPUT },
    );

    expect(result.applied).toBe(1);
    expect(result.text).toContain("<aguaphone-inline-card>");
    expect(result.text).toContain("<ul><li>A</li><li>B</li></ul>");
    expect(result.text).not.toContain("```html");
  });
});
